"""Screenplay for "Understanding America — Episode 1: From Vikings to Columbus".

Each scene has:
  kind   – which visual renderer draws it (see scenes.py)
  mood   – drives the procedural score (see music.py)
  vo     – narration, one caption chunk per list item (may be empty)
  cues   – visual events keyed to the index of the vo chunk that triggers them
Everything else is passed through to the renderer as parameters.
"""

# Pronunciation hints used only for the TTS engine (captions keep the real spelling).
SAY = {
    "Skraelings": "Skraylings",
    "Skraeling": "Skrayling",
    "Beothuk": "Bay-othuk",
    "Taíno": "Tie-eeno",
    "L'Anse aux Meadows": "Lonce oh Meadows",
    "Gudrid": "Goodrid",
    "Karlsefni": "Karl-sevnee",
    "Bjarni Herjólfsson": "Byarni Her-yolfsson",
    "Bjarni": "Byarni",
    "Eiríkr": "Ay-reeker",
    "maravedís": "mara-vedees",
    "Waldseemüller": "Vald-zay-muller",
    "Valladolid": "Vah-ya-doleed",
    "fukú": "foo-koo",
    "encomienda": "enco-mee-enda",
    "Shanawdithit": "Shana-dithit",
    "Guadeloupe": "Gwada-loop",
    "Cristoforo Colombo": "Cristofforo Colombo",
    "Cristóbal Colón": "Cristobal Colone",
    "Montesinos": "Monte-seenos",
    "Bartolomé de las Casas": "Bartolomay de las Casas",
    "Las Casas": "las Casas",
    "Helluland": "Hellooland",
    "Markland": "Markland",
    "Vinland": "Vinland",
    "Lothbrok": "Lothbrock",
    "Hardrada": "Hard-rahda",
    "Freydis": "Fraydis",
    "Rodrigo de Triana": "Rodreego de Tree-ahna",
    "Niña": "Neenya",
    "Santa María": "Santa Maria",
    "La Navidad": "La Nahvidad",
    "Española": "Espanyola",
    "Hispaniola": "Hispanyola",
    "Amerigo Vespucci": "Amerigo Vespoochy",
    "Vespucci": "Vespoochy",
    "hamaca": "ha-mahka",
    "Huracán": "Oora-kahn",
    "Barbacoa": "Barba-koa",
    "Sabana": "Sa-bahna",
    "Batata": "Ba-tahta",
    "Canoa": "Ka-noa",
    "Tabaco": "Ta-bahco",
    "Thorfinn": "Thorfin",
    "Genoa": "Jenoa",
}

N = "north"

SCENES = [
    # ------------------------------------------------------------------ COLD OPEN
    dict(id="open", kind="sea", mood="mystery", ship="longship", n=1, weather="storm",
         tod="night", lightning=True,
         vo=["A thousand years ago, a wooden ship with a dragon on its prow sailed out of the northern mist.",
             "The men aboard did not know it, but they had just found a new world.",
             "Five centuries later, it would be found again...",
             "by a man who never understood what he had found."]),
    dict(id="title", kind="title", mood="hit", hold=7.0, vo=[]),

    # ------------------------------------------------------------------ WHY AMERICA
    dict(id="why", kind="rome", mood="wonder",
         vo=["The United States is the most powerful political entity that has ever existed.",
             "Call it a superpower. Some would call it an empire.",
             "Two thousand years after Rome, we still live inside Rome's echo.",
             "January. February. August, named for the emperor Augustus.",
             "Latin still names every plant and animal known to science.",
             "America's shadow over the next two thousand years may be longer still.",
             "And yet it may be the most misunderstood nation on Earth."],
         cues={2: "words"}),
    dict(id="books", kind="books", mood="wonder",
         vo=["So this is a journey through American history, told in order, from the very beginning,",
             "through one hundred of the finest books ever written about it.",
             "Not as an expert. As a learner.",
             "It begins with Tony Horwitz's 'A Voyage Long and Strange', a book in three parts.",
             "Discovery. Conquest. Settlement.",
             "Today... Discovery."],
         cues={3: "book", 4: "parts", 5: "discovery"}),

    # ------------------------------------------------------------------ I. THE NORSEMEN
    dict(id="ch1", kind="chapter", mood="hit", num="I", title="THE NORSEMEN", sub="793 – 1066 AD", vo=[]),
    dict(id="raid", kind="raid", mood="epic", stamp="LINDISFARNE, ENGLAND — 793 AD",
         vo=["The year is 793.",
             "Longships beach on Lindisfarne, a holy island off the coast of England.",
             "The raiders sack its monastery and carry off its gold.",
             "The Viking Age has begun."]),
    dict(id="fjord", kind="fjord", mood="epic", stamp="SCANDINAVIA",
         vo=["Who were they? Norse people, from what is now Norway, Denmark and Sweden.",
             "Most of them were simply farmers.",
             "Only those who went raiding, sailing out to plunder and conquer, were truly called Vikings.",
             "Today we give that name to all of them."]),
    dict(id="legends", kind="portraits", mood="epic",
         people=[dict(name="RAGNAR LOTHBROK", epi="Half man, half legend", look="viking", c=(120, 150, 190)),
                 dict(name="ROLLO", epi="Founder of Normandy", look="viking", c=(150, 130, 100)),
                 dict(name="WILLIAM THE CONQUEROR", epi="England, 1066", look="king", c=(190, 150, 60)),
                 dict(name="HARALD HARDRADA", epi="The last great Viking king", look="viking", c=(170, 70, 60))],
         vo=["It was an age of legends. Ragnar Lothbrok, half myth, half man.",
             "Rollo, the Viking who took a piece of France: Normandy, the land of the Northmen.",
             "His descendant, William the Conqueror, would seize England in 1066.",
             "Every English monarch since descends from him.",
             "That same year, the last great Viking king, Harald Hardrada, died trying to conquer England.",
             "And with him, the Viking Age came to an end."],
         cues={0: 0, 1: 1, 2: 2, 4: 3}),
    dict(id="toiceland", kind="map", mood="wonder", view=(-40, 20, 50, 72),
         routes=[dict(pts=[(5.3, 60.4), (-6.5, 62.0), (-21.9, 64.1)], cue=1)],
         labels=[dict(t="NORWAY", at=(9, 61.5), cue=0), dict(t="ICELAND", at=(-18.5, 65.3), cue=1),
                 dict(t="ENGLAND", at=(-1.5, 52.5), cue=0), dict(t="NORMANDY", at=(0.5, 48.8), cue=0)],
         vo=["But before it ended, the Norse pushed west, across the grey North Atlantic.",
             "To Iceland: a raw land of volcanoes and geysers,",
             "whose ash made the soil surprisingly fertile.",
             "There, they settled."]),
    dict(id="iceland", kind="iceland", mood="mystery", stamp="ICELAND — c. 870 AD", vo=[], hold=4.5),

    # ------------------------------------------------------------------ II. ERIK THE RED
    dict(id="ch2", kind="chapter", mood="hit", num="II", title="ERIK THE RED", sub="c. 985 AD", vo=[]),
    dict(id="erik", kind="portraits", mood="tension",
         people=[dict(name="ERIK THE RED", epi="Exile. Killer. Explorer.", look="viking_red", c=(200, 50, 30))],
         vo=["Among them was a man named Eiríkr. Erik the Red.",
             "A hothead. A killer.",
             "Banished from his homeland for murder, he settled in Iceland... and killed again.",
             "Banished once more, he did the only thing left to do.",
             "He sailed west."],
         cues={0: 0}),
    dict(id="togreenland", kind="map", mood="tension", view=(-60, -10, 55, 75),
         routes=[dict(pts=[(-21.9, 64.1), (-32, 64.5), (-42, 61.5), (-45.5, 61.1)], cue=0)],
         labels=[dict(t="ICELAND", at=(-18.5, 65.3), cue=0), dict(t="GREENLAND", at=(-40, 70), cue=1),
                 dict(t="Brattahlíð", at=(-45.5, 61.1), cue=1, small=True, dot=True)],
         vo=["Around the year 985, he found a vast island.",
             "The climate was warmer then. But even so, he was selling a dream.",
             "He called it Greenland."]),
    dict(id="greenland", kind="greenland", mood="wonder", stamp="GREENLAND",
         vo=["Today, around eighty percent of it lies beneath a thick sheet of ice.",
             "Erik may have been history's first great real-estate salesman.",
             "It worked. Settlers followed, and Erik ruled them as their overlord."]),
    dict(id="bjarni", kind="sea", mood="mystery", ship="longship", n=1, weather="fog", tod="day",
         coast="forest", stamp="SOMEWHERE WEST OF GREENLAND",
         vo=["Then a sailor named Bjarni Herjólfsson, bound for Greenland, was caught in a storm and blown far off course.",
             "Out of the fog rose a strange, forested coast.",
             "His crew begged to go ashore. Bjarni refused.",
             "Nothing worth seeing here, he said, and turned back.",
             "For a thousand years, he has been remembered as a man of spectacularly poor judgment.",
             "He had just seen North America."],
         cues={1: "coast"}),

    # ------------------------------------------------------------------ III. VINLAND
    dict(id="ch3", kind="chapter", mood="hit", num="III", title="VINLAND", sub="c. 1000 AD", vo=[]),
    dict(id="leif", kind="portraits", mood="wonder",
         people=[dict(name="LEIF ERIKSON", epi="Son of Erik the Red", look="viking_young", c=(90, 160, 200))],
         vo=["Erik's son Leif was nothing like his father.",
             "Steady. Calm. Careful.",
             "He bought Bjarni's ship, gathered a crew,",
             "and went looking for the land that Bjarni had refused."],
         cues={0: 0}),
    dict(id="tovinland", kind="map", mood="epic", view=(-78, -30, 42, 72),
         routes=[dict(pts=[(-45.5, 61.1), (-55, 64), (-63, 66.5)], cue=0),
                 dict(pts=[(-63, 66.5), (-62, 60), (-59, 55.5)], cue=1),
                 dict(pts=[(-59, 55.5), (-56.5, 53), (-55.5, 51.6)], cue=2)],
         labels=[dict(t="GREENLAND", at=(-42, 69), cue=0),
                 dict(t="HELLULAND", sub="Land of Stone Slabs · Baffin Island", at=(-68, 67.5), cue=0),
                 dict(t="MARKLAND", sub="Forest Land · Labrador", at=(-67, 56.5), cue=1),
                 dict(t="VINLAND", sub="Newfoundland", at=(-61, 50), cue=2, dot=(-55.5, 51.6))],
         vo=["First came a coast of bare, flat rock. Helluland: the Land of Stone Slabs. Baffin Island.",
             "Then a coast of endless forest. Markland, the Forest Land. Labrador.",
             "And then, further south, a place where they finally came ashore, and built houses.",
             "Around the year one thousand, Europeans were living in North America."]),
    dict(id="grapes", kind="vines", mood="wonder", stamp="VINLAND",
         vo=["One of Leif's men wandered off, and came back... drunk.",
             "In the far north, where grapes do not grow, this was a mystery.",
             "He had found grapes, he said. Wild vines, heavy with fruit.",
             "And so the land had its name. Vinland. The Land of Wine.",
             "Leif sailed home a legend. Leif the Lucky.",
             "He never went back."],
         cues={3: "title"}),

    # ------------------------------------------------------------------ IV. THE SKRAELINGS
    dict(id="ch4", kind="chapter", mood="hit", num="IV", title="FIRST CONTACT", sub="c. 1004 AD", vo=[]),
    dict(id="canoes", kind="beach", mood="tension", variant="canoes", stamp="VINLAND — THORVALD'S VOYAGE",
         vo=["Leif's brother Thorvald followed in his footsteps, and found the houses.",
             "One day, his men saw three humps on the beach.",
             "Not rocks. Canoes, with men sheltering beneath them.",
             "The Norse attacked. Eight were killed.",
             "One escaped."],
         cues={2: "reveal", 3: "attack", 4: "escape"}),
    dict(id="arrows", kind="beach", mood="epic", variant="arrows",
         vo=["He came back with a fleet.",
             "Arrows darkened the sky.",
             "Thorvald was struck, and knew the wound was fatal.",
             "He asked to be buried in the land he had hoped to call home.",
             "He was among the first Europeans known to die in the Americas."],
         cues={1: "volley"}),
    dict(id="skraeling", kind="word", mood="mystery", word="SKRÆLING",
         meaning="“wretch”  ·  “screecher”",
         vo=["The Norse called the natives Skraelings. Roughly: wretches. Screechers.",
             "A word like 'barbarian'.",
             "Of course, to the natives, these pale, red-bearded strangers must have looked every bit as strange."]),

    # ------------------------------------------------------------------ V. GUDRID & FREYDIS
    dict(id="ch5", kind="chapter", mood="hit", num="V", title="THE DAUGHTER OF ERIK", sub="c. 1010 AD", vo=[]),
    dict(id="gudrid", kind="portraits", mood="wonder",
         people=[dict(name="THORSTEIN", epi="Died before reaching Vinland", look="viking", c=(110, 110, 140)),
                 dict(name="GUDRID & THORFINN KARLSEFNI", epi="Settlers of Vinland", look="woman", c=(180, 140, 90))],
         vo=["Another brother, Thorstein, set out to bring Thorvald's body home, but fell sick and died.",
             "His widow, Gudrid, remarried a merchant captain, Thorfinn Karlsefni.",
             "Together they sailed to Vinland, with livestock and settlers.",
             "This time, there was trade."],
         cues={0: 0, 1: 1}),
    dict(id="trade", kind="icons", mood="wonder",
         left=dict(title="THE NORSE", items=["\U0001f95b", "\U0001f9c0"], names=["milk", "cheese"]),
         right=dict(title="THE NATIVES", items=["\U0001f98a", "\U0001f3f9"], names=["furs", "goods"]),
         vo=["The natives, who had never seen dairy, traded furs and goods for milk and cheese.",
             "And in Vinland, Gudrid gave birth to a son. Snorri.",
             "The first child of European descent known to be born in the Americas."],
         cues={1: "snorri"}),
    dict(id="freydis", kind="portraits", mood="dark",
         people=[dict(name="FREYDIS EIRÍKSDÓTTIR", epi="Daughter of Erik the Red", look="woman_dark", c=(160, 20, 20))],
         vo=["Then came Erik's daughter, Freydis. As fierce as her father.",
             "She sailed with two brothers who captained a second ship.",
             "They agreed on equal crews. She secretly smuggled five extra warriors aboard her own.",
             "Numbers matter.",
             "In Vinland, she drove the brothers out of Leif's houses."],
         cues={0: 0}),
    dict(id="night", kind="night", mood="dark",
         vo=["Then one night she came back to bed, cold and barefoot,",
             "and told her husband that the brothers had struck and insulted her.",
             "If you were a man, she said, you would avenge me."]),
    dict(id="axe", kind="axe", mood="dark",
         vo=["Her men killed the brothers' crew.",
             "When they refused to kill the five women, Freydis took up an axe and did it herself.",
             "Later, heavily pregnant, she faced down a native attack.",
             "But the Norse were few. The natives were many, and could always bring more.",
             "The Norse sailed away, and never came back."],
         cues={1: "strike", 4: "leave"}),

    # ------------------------------------------------------------------ VI. THE FORGOTTEN WORLD
    dict(id="ch6", kind="chapter", mood="hit", num="VI", title="THE FORGOTTEN WORLD", sub="1000 – 1829", vo=[]),
    dict(id="lanse", kind="sod", mood="mystery", stamp="L'ANSE AUX MEADOWS, NEWFOUNDLAND",
         vo=["Then the world forgot.",
             "For nearly five hundred years, no one in Europe remembered that there was land to the west.",
             "Not until the 1960s did archaeologists find the Norse settlement at L'Anse aux Meadows, on the northern tip of Newfoundland.",
             "Low sod houses, dark as hobbit holes.",
             "It became one of the very first UNESCO World Heritage Sites."],
         cues={2: "dig", 4: "unesco"}),
    dict(id="beothuk", kind="fires", mood="tragic", stamp="NEWFOUNDLAND — THE BEOTHUK",
         vo=["And the people the Norse had met?",
             "When Europeans returned, English, French, Portuguese and Basque, to fish and to hunt,",
             "they came into conflict with the island's natives: the Beothuk.",
             "They were hunted, pushed from the coast, starved.",
             "In 1823, three Beothuk women were captured. Two soon died.",
             "The last, Shanawdithit, died of tuberculosis in 1829.",
             "After her, no Beothuk was ever seen again."],
         cues={3: "fade", 4: "three", 6: "last"}),
    dict(id="bridge", kind="sea", mood="mystery", ship="none", weather="calm", tod="dawn",
         vo=["Today, Newfoundland is part of Canada.",
             "And five centuries after Leif, the second discovery was about to begin,",
             "by a man who was always lost."]),

    # ------------------------------------------------------------------ VII. THE ADMIRAL
    dict(id="ch7", kind="chapter", mood="hit", num="VII", title="THE GENOESE", sub="1451 – 1492", vo=[]),
    dict(id="genoa", kind="portraits", mood="wonder",
         people=[dict(name="CRISTOFORO COLOMBO", epi="Christopher Columbus · Genoa, c. 1451", look="columbus", c=(200, 160, 70))],
         vo=["Cristoforo Colombo. Christopher Columbus.",
             "Born in Genoa around 1451, the son of a weaver.",
             "He went to sea, sailed the coast of West Africa and its slave ports,",
             "and made his life in Portugal and in Spain."],
         cues={0: 0}),
    dict(id="flat", kind="globe", mood="mystery",
         vo=["A popular myth says that Europe believed the world was flat.",
             "It did not. Educated Europeans knew the Earth was a sphere.",
             "The only question was: how big?"],
         cues={1: "round", 2: "size"}),
    dict(id="constantinople", kind="city", mood="epic", stamp="CONSTANTINOPLE — 1453",
         vo=["In 1453, the Ottoman Turks conquered Constantinople.",
             "The old roads to the riches of the East, to India's spices, to the China of Marco Polo and the Great Khan, were cut.",
             "Whoever found a new way there would become impossibly rich."],
         cues={0: "fall"}),
    dict(id="portuguese", kind="map", mood="tension", view=(-45, 85, -42, 50),
         routes=[dict(pts=[(-9.1, 38.7), (-18, 25), (-18, 12), (-8, 3), (9, -5), (12, -18), (16, -32), (18.5, -34.8)], cue=1),
                 dict(pts=[(18.5, -34.8), (28, -33), (40, -15), (43, -2), (55, 8), (75.8, 11.3)], cue=2),
                 dict(pts=[(-9.1, 38.7), (-30, 33), (-45, 28)], cue=3, color="red")],
         labels=[dict(t="PORTUGAL", at=(-8, 41), cue=0),
                 dict(t="CAPE OF GOOD HOPE", sub="Dias, 1488", at=(20, -38), cue=1, dot=(18.5, -34.4)),
                 dict(t="INDIA", sub="da Gama, 1498", at=(78, 20), cue=2, dot=(75.8, 11.3)),
                 dict(t="WEST?", at=(-38, 38), cue=3)],
         vo=["The Portuguese went south, feeling their way around Africa.",
             "Bartolomeu Dias rounded the Cape of Good Hope in 1488.",
             "A decade later, Vasco da Gama would reach India.",
             "Columbus had a different idea. Go west."]),
    dict(id="distance", kind="compare", mood="tension",
         a=dict(label="COLUMBUS'S ESTIMATE", value=5000, unit="km"),
         b=dict(label="THE REAL DISTANCE", value=18000, unit="km"),
         vo=["He believed Asia lay only about five thousand kilometers west of Spain.",
             "The real distance is closer to eighteen thousand.",
             "He was wrong by an ocean, and a continent."],
         cues={1: "b", 2: "gap"}),
    dict(id="court", kind="court", mood="epic", stamp="THE CROWN OF CASTILE",
         vo=["Portugal laughed him out of court.",
             "But Spain, newly united under Ferdinand and Isabella, and hungry to outdo its rivals, listened.",
             "Columbus promised them the thing every kingdom craved.",
             "Gold."],
         cues={1: "royals", 3: "gold"}),

    # ------------------------------------------------------------------ VIII. 1492
    dict(id="ch8", kind="chapter", mood="hit", num="VIII", title="1492", sub="The Ocean Sea", vo=[]),
    dict(id="fleet", kind="sea", mood="epic", ship="caravel", n=3, weather="calm", tod="dawn",
         names=["NIÑA", "PINTA", "SANTA MARÍA"], stamp="PALOS DE LA FRONTERA — AUGUST 1492",
         vo=["Three ships: the Niña, the Pinta, and the Santa María.",
             "After resupplying in the Canary Islands, they sailed west, into the unknown."]),
    dict(id="logs", kind="logs", mood="tension",
         vo=["As days became weeks, his sailors grew afraid.",
             "Columbus kept two logs: the true distance, and a shorter one he showed his crew.",
             "No one had ever sailed so long into the open ocean."],
         cues={1: "logs"}),
    dict(id="land", kind="sea", mood="epic", ship="caravel", n=1, weather="calm", tod="night",
         coast="light", stamp="12 OCTOBER 1492 — 2:00 AM",
         vo=["The crown promised a lifetime pension of ten thousand maravedís a year to the first man to sight land.",
             "On the twelfth of October, 1492, a lookout on the Pinta, Rodrigo de Triana, cried out.",
             "Land!",
             "But Columbus claimed he had seen a light the night before, and took the reward for himself."],
         cues={2: "coast"}),
    dict(id="landing", kind="landing", mood="wonder", stamp="THE BAHAMAS — OCTOBER 1492",
         vo=["Somewhere in the Bahamas, they waded ashore and kissed the sand.",
             "The people who greeted them, the Taíno, were friendly, curious and generous.",
             "They traded parrots and cotton for glass beads and little bells.",
             "The Spaniards were astonished. The islanders were taller, healthier, and far cleaner than the Europeans.",
             "But they had no metal.",
             "When they were shown swords, they grasped them by the blade, and cut themselves."],
         cues={1: "taino", 2: "trade"}),
    dict(id="quote", kind="quote", mood="dark",
         quote="“They should be good servants.”", who="CHRISTOPHER COLUMBUS · JOURNAL, OCTOBER 1492",
         vo=["That night, Columbus wrote in his journal:",
             "They should be good servants."]),
    dict(id="caribbean", kind="map", mood="tension", view=(-88, -58, 8, 30),
         routes=[dict(pts=[(-74.5, 24.05), (-75.5, 22.8), (-76.2, 21.3)], cue=1),
                 dict(pts=[(-76.2, 21.3), (-74.5, 20.5), (-72.8, 20.0), (-72.1, 19.75)], cue=2)],
         labels=[dict(t="SAN SALVADOR", sub="First landfall", at=(-72.5, 25.8), cue=0, dot=(-74.5, 24.05)),
                 dict(t="CUBA", at=(-79.5, 22.6), cue=1),
                 dict(t="HISPANIOLA", sub="Haiti · Dominican Republic", at=(-70.5, 20.9), cue=2),
                 dict(t="FLORIDA", at=(-82, 28), cue=0)],
         vo=["Tiny flakes of gold glinted in their ornaments. Gold meant a source, somewhere.",
             "Columbus pushed on to Cuba, sure that he was near the Ganges,",
             "then east, to a great island he named La Isla Española: Hispaniola.",
             "Today it holds Haiti and the Dominican Republic."]),
    dict(id="navidad", kind="wreck", mood="tension", stamp="CHRISTMAS EVE, 1492",
         vo=["On Christmas Eve, 1492, the Santa María ran aground and was lost.",
             "From her timbers, Columbus built a fort. La Navidad, the Nativity.",
             "He left thirty-nine men behind with orders: find the gold, and do not make enemies of the natives.",
             "Then he sailed home."],
         cues={1: "fort", 3: "sail"}),
    dict(id="triumph", kind="court", mood="epic", stamp="BARCELONA — 1493", variant="triumph",
         vo=["In Spain, Columbus announced that he had reached the Indies, where rivers ran with gold.",
             "He was named Admiral of the Ocean Sea, and governor of every land he found,",
             "with a share of all their riches."],
         cues={0: "royals", 1: "title", 2: "gold"}),

    # ------------------------------------------------------------------ IX. RIVERS OF GOLD
    dict(id="ch9", kind="chapter", mood="hit", num="IX", title="RIVERS OF GOLD", sub="1493 – 1496", vo=[]),
    dict(id="armada", kind="sea", mood="epic", ship="caravel", n=17, weather="calm", tod="day",
         stamp="THE SECOND VOYAGE — 1493",
         vo=["In 1493 he returned. Not with three ships, but seventeen.",
             "Twelve hundred men, many of them gentlemen hungry for fortune.",
             "Island-hopping, he named as he went. Dominica. Guadeloupe. The Virgin Islands.",
             "Whatever those islands were called before, no one remembers."],
         cues={0: "count"}),
    dict(id="ruins", kind="ruins", mood="dark", stamp="LA NAVIDAD — NOVEMBER 1493",
         vo=["At La Navidad, he found only corpses.",
             "Through captives who now spoke Spanish, he learned why.",
             "His men had seized native women, and the islanders had killed them all."]),
    dict(id="quota", kind="quota", mood="dark",
         vo=["Columbus was no longer an explorer. He was a governor. And a disastrous one.",
             "He enslaved the island.",
             "Every native over fourteen owed a quota of gold, every three months.",
             "Those who failed were brutally punished. Many were mutilated, or killed."],
         cues={2: "quota", 3: "blood"}),
    dict(id="split", kind="split", mood="tragic",
         vo=["Men were sent to the mines. Women, to the cassava fields. Apart, for months at a time.",
             "Children went uncared for, and died.",
             "Exhausted and in despair, people stopped having children at all.",
             "Within a decade, perhaps a third of the island's people were dead."],
         cues={1: "children", 3: "third"}),
    dict(id="slaveship", kind="sea", mood="tragic", ship="caravel", n=1, weather="storm", tod="dusk",
         stamp="1496", dark=True,
         vo=["Still, there was no great gold.",
             "So in 1496, Columbus sailed home with enslaved Taíno instead.",
             "Many died on the crossing, and were thrown overboard. Most of the rest died in Spain.",
             "His reputation began to crack. And the crown ended his monopoly on voyages west."]),

    # ------------------------------------------------------------------ X. ADMIRAL IN CHAINS
    dict(id="ch10", kind="chapter", mood="hit", num="X", title="THE ADMIRAL IN CHAINS", sub="1498 – 1506", vo=[]),
    dict(id="pear", kind="globe", mood="mystery", variant="pear",
         vo=["In 1498, on his third voyage, he steered by the stars, and got lost again.",
             "He reached the coast of Venezuela. South America.",
             "Faced with a vast river pouring fresh water into the sea,",
             "he wondered whether the Earth was shaped like a pear, with the Garden of Eden at its tip."],
         cues={3: "pear"}),
    dict(id="chains", kind="chains", mood="dark", stamp="SANTO DOMINGO — 1500",
         vo=["On Hispaniola, the colony was in chaos. Infighting. Mutiny. Rebellion.",
             "In 1500, the crown sent an investigator.",
             "He arrested the Admiral of the Ocean Sea, put him in chains, and shipped him back to Spain."],
         cues={2: "chains"}),
    dict(id="jamaica", kind="sea", mood="tragic", ship="wreck", n=1, weather="calm", tod="dusk", coast="palm",
         stamp="JAMAICA — 1503",
         vo=["Columbus talked his way into one last voyage, in 1502.",
             "His worm-eaten ships fell apart, and he was marooned on Jamaica for a year.",
             "He returned to Spain in 1504, arthritic and broken.",
             "In 1506, he died, still insisting he had reached the Indies."]),

    # ------------------------------------------------------------------ XI. A STOLEN NAME
    dict(id="ch11", kind="chapter", mood="hit", num="XI", title="A STOLEN NAME", sub="1507", vo=[]),
    dict(id="vespucci", kind="portraits", mood="wonder",
         people=[dict(name="AMERIGO VESPUCCI", epi="Florentine navigator · storyteller", look="vespucci", c=(80, 140, 120))],
         vo=["Meanwhile, a Florentine named Amerigo Vespucci claimed to have reached the new lands in 1497. Probably a lie.",
             "He told of women so tall that, kneeling, they towered over standing men.",
             "His stories sold. Europe was hooked."],
         cues={0: 0}),
    dict(id="naming", kind="naming", mood="epic",
         vo=["In 1507, a German mapmaker, Martin Waldseemüller, understood that this was not India, but a new world,",
             "and named it after Vespucci.",
             "America.",
             "He later changed his mind. But the great cartographer Mercator used the name again, and it stuck.",
             "Columbus got the District of Columbia, and a country, Colombia.",
             "A salesman got two continents."],
         cues={2: "america", 4: "columbia", 5: "continents"}),

    # ------------------------------------------------------------------ XII. THE WANDERING BONES
    dict(id="ch12", kind="chapter", mood="hit", num="XII", title="THE WANDERING BONES", sub="1506 – today", vo=[]),
    dict(id="bones", kind="map", mood="mystery", view=(-92, 2, 10, 50),
         routes=[dict(pts=[(-4.72, 41.65), (-5.98, 37.39)], cue=1),
                 dict(pts=[(-5.98, 37.39), (-20, 30), (-50, 22), (-69.9, 18.47)], cue=2),
                 dict(pts=[(-69.9, 18.47), (-75, 20.5), (-82.36, 23.13)], cue=3),
                 dict(pts=[(-82.36, 23.13), (-60, 32), (-25, 38), (-5.98, 37.39)], cue=5)],
         labels=[dict(t="VALLADOLID", sub="1506", at=(-2.5, 44), cue=0, dot=(-4.72, 41.65)),
                 dict(t="SEVILLE", sub="1509", at=(-9, 34.5), cue=1, dot=(-5.98, 37.39)),
                 dict(t="SANTO DOMINGO", sub="1541", at=(-66, 15.5), cue=2, dot=(-69.9, 18.47)),
                 dict(t="HAVANA", sub="1795", at=(-84, 26.5), cue=3, dot=(-82.36, 23.13)),
                 dict(t="SEVILLE", sub="1898", at=(-12, 40), cue=5)],
         vo=["Even in death, Columbus kept wandering. He was buried in Valladolid in 1506.",
             "Moved to Seville in 1509.",
             "In 1541, shipped across the Atlantic to the cathedral of Santo Domingo, and buried in an unmarked spot, for fear of pirates.",
             "In 1795, as Spain surrendered Hispaniola to France, his bones were moved to Havana.",
             "Mark Twain later joked that Havana displayed two skulls of Columbus: one as a boy, and one as a man.",
             "And when Spain lost Cuba in 1898, the bones went back to Seville."]),
    dict(id="leadbox", kind="crypt", mood="mystery", stamp="SANTO DOMINGO CATHEDRAL — 1877",
         vo=["But in 1877, workers in Santo Domingo's cathedral found a lead box.",
             "Inside: bones, and an inscription.",
             "Illustrious and distinguished man, Don Cristóbal Colón.",
             "So whose bones went to Seville? His son Diego's?",
             "Spain and the Dominican Republic both still claim him."],
         cues={1: "open", 2: "text"}),
    dict(id="lighthouse", kind="lighthouse", mood="wonder", stamp="FARO A COLÓN — SANTO DOMINGO",
         vo=["In Santo Domingo stands his tomb: a vast monument called the Columbus Lighthouse.",
             "Its searchlights can project a cross into the clouds, visible for miles.",
             "But on an island of frequent blackouts, the lights mostly stay dark.",
             "Dominicans speak of the fukú. The curse of Columbus.",
             "Put his name on something, they say, and watch it fail."],
         cues={1: "on", 2: "off"}),

    # ------------------------------------------------------------------ XIII. THE DESTRUCTION OF THE INDIES
    dict(id="ch13", kind="chapter", mood="hit", num="XIII", title="THE DESTRUCTION OF THE INDIES", sub="1502 – 1550", vo=[]),
    dict(id="lascas", kind="portraits", mood="tragic",
         people=[dict(name="BARTOLOMÉ DE LAS CASAS", epi="Colonist · Priest · Witness", look="priest", c=(150, 120, 170))],
         vo=["In 1502, an eighteen-year-old Spaniard named Bartolomé de las Casas arrived on Hispaniola.",
             "He became a colonist, and a priest.",
             "The system around him was called the encomienda.",
             "With a stroke of the pen, the land belonged to the crown, and the Taíno were parcelled out to Spanish masters to work it.",
             "Slavery, in all but name."],
         cues={0: 0}),
    dict(id="sermon", kind="church", mood="tragic", stamp="SANTO DOMINGO — ADVENT, 1511",
         vo=["In 1511, a friar named Antonio de Montesinos thundered from the pulpit.",
             "Are these not men? Are you not obliged to love them as yourselves?",
             "Las Casas had a change of heart.",
             "He gave up his own natives, and spent the rest of his life bearing witness."],
         cues={1: "words"}),
    dict(id="account", kind="book", mood="dark",
         title="A SHORT ACCOUNT OF THE DESTRUCTION OF THE INDIES", year="1552",
         vo=["His book, A Short Account of the Destruction of the Indies, records what he saw with his own eyes.",
             "Spaniards who forced natives to carry them everywhere.",
             "Men who wagered on whether they could cut a person in two with a single stroke.",
             "People burned over slow fires."]),
    dict(id="census", kind="census", mood="tragic",
         vo=["In 1492, Hispaniola was home to at least half a million people. Perhaps several million.",
             "In 1514, a Spanish census counted fewer than twenty-three thousand working-age natives.",
             "Within a few more decades, the Taíno of Hispaniola were effectively gone.",
             "There is only one word for it."],
         cues={1: "drop", 2: "gone", 3: "word"}),
    dict(id="africa", kind="sea", mood="tragic", ship="caravel", n=4, weather="storm", tod="dusk", dark=True,
         stamp="THE ATLANTIC",
         vo=["Las Casas, desperate to spare the Taíno, urged that enslaved Africans be brought to do the work instead,",
             "a position he would later bitterly regret.",
             "It became standard practice across the Americas.",
             "Wherever the native population collapsed, ships arrived from Africa."]),
    dict(id="words", kind="words", mood="wonder",
         pairs=[("hamaca", "hammock"), ("canoa", "canoe"), ("huracán", "hurricane"),
                ("barbacoa", "barbecue"), ("sabana", "savanna"), ("tabaco", "tobacco"), ("batata", "potato")],
         crops=["\U0001f33d", "\U0001f954", "\U0001f336️", "\U0001f95c", "\U0001f34d", "\U0001f345"],
         vo=["And yet, the Taíno live on, in words.",
             "Hamaca: hammock. Canoa: canoe. Huracán: hurricane.",
             "Barbacoa: barbecue. Sabana: savanna. Tabaco. And batata: potato.",
             "And the crops of the Americas, maize, cassava, potatoes, peppers, peanuts, pineapples,",
             "now feed the whole world."],
         cues={1: 0, 2: 3, 3: "crops"}),

    # ------------------------------------------------------------------ XIV. WHY SPAIN WON
    dict(id="ch14", kind="chapter", mood="hit", num="XIV", title="WHY THE VIKINGS FAILED", sub="and Spain did not", vo=[]),
    dict(id="versus", kind="versus", mood="epic",
         rows=[("STEEL", True, True), ("HORSES", False, True), ("FIREARMS", False, True),
               ("A KINGDOM'S TREASURY", False, True), ("ENDLESS REINFORCEMENTS", False, True)],
         vo=["Why did the Vikings fail, where Spain succeeded?",
             "The Norse had steel too. But the Spaniards had more.",
             "Horses, which no one in the Americas had ever seen. Some believed that horse and rider were a single, monstrous creature.",
             "Firearms. Crude and inaccurate, but terrifying in their thunder.",
             "And above all, money and numbers.",
             "The Vinland voyages were small family ventures: one family, four voyages.",
             "Spain had the treasury of a kingdom behind it, and ship after ship after ship."],
         cues={1: 0, 2: 1, 3: 2, 4: 3, 6: 4}),
    dict(id="empire", kind="map", mood="epic", view=(-125, -30, -45, 45), spanish=True,
         labels=[dict(t="NEW SPAIN", at=(-102, 24), cue=0), dict(t="PERU", at=(-73, -12), cue=0),
                 dict(t="UNITED STATES", sub="More Spanish speakers than Spain", at=(-98, 39), cue=1)],
         routes=[],
         vo=["Spain would go on to colonize most of South and Central America, and much of North America.",
             "Today, more Spanish speakers live in the United States than in Spain."]),
    dict(id="usa", kind="map", mood="hopeful", view=(-100, -55, 22, 52),
         routes=[dict(pts=[(-10, 45), (-40, 40), (-65, 38), (-76.78, 37.21)], cue=2),
                 dict(pts=[(-10, 50), (-40, 46), (-62, 43), (-70.66, 41.96)], cue=2)],
         labels=[dict(t="JAMESTOWN", sub="1607", at=(-83, 36), cue=2, dot=(-76.78, 37.21)),
                 dict(t="PLYMOUTH", sub="1620", at=(-73, 45), cue=2, dot=(-70.66, 41.96)),
                 dict(t="THE CARIBBEAN", sub="Columbus", at=(-73, 23.5), cue=0),
                 dict(t="NEWFOUNDLAND", sub="The Norse", at=(-60, 51), cue=0)],
         vo=["Columbus never saw the land that became the United States. Neither did the Vikings.",
             "But they opened the door.",
             "The English would come later, Jamestown in 1607, the Pilgrims at Plymouth in 1620,",
             "and they would build something very different."]),
    dict(id="judgment", kind="sea", mood="hopeful", ship="none", weather="calm", tod="dusk",
         vo=["History is not here to pass judgment.",
             "It is a story of wars, of conquest, of civilizations that vanished.",
             "The point is to understand cause and effect.",
             "How the modern world came to be the way it is."]),
    dict(id="next", kind="next", mood="finale",
         vo=["This was Discovery.",
             "Next time: Conquest... and Settlement."],
         cues={1: "next"}),
    dict(id="end", kind="end", mood="end", hold=9.0, vo=[]),
]
